version: '3'
services:
  computer-craft-deploy:
    build: .
    user: ${UID}:${UID}
    environment:
      DISCORD_APP_TOKEN: ${DISCORD_APP_TOKEN}
      REPOSITORY_PREFIX: ${REPOSITORY_PREFIX}
      COMPUTER_CRAFT_DIR: ${COMPUTER_CRAFT_DIR}
      SCRIPTS_DIR: ${SCRIPTS_DIR}
    restart: unless-stopped
