apiVersion: v1
kind: Pod
metadata:
  name: computer-craft-deploy
  namespace: minecraft-wd-forge-1710
  labels:
    name: computer-craft-deploy
spec:
  containers:
  - name: computer-craft-deploy
    image: docker.io/shosatojp/computer-craft-deploy
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /computer
        name: minecraft
        subPath: server/world/computer
    env:
      - name: DISCORD_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: computer-craft-deploy
            key: DISCORD_BOT_TOKEN
    # kubectl create secret generic computer-craft-deploy --from-literal=DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
      - name: REPOSITORY_PREFIX
        value: https://github.com/uec-world-dominators/computer-craft-tools/
      - name: COMPUTER_CRAFT_DIR
        value: /computer/
      - name: SCRIPTS_DIR
        value: scripts
  volumes:
    - name: minecraft
      persistentVolumeClaim:
          claimName: minecraft
