apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: docker.io/shosatojp/computer-craft-deploy
      docker:
          dockerfile: Dockerfile
          noCache: false
          squash: false
deploy:
  kubectl:
    manifests:
      - k8s-*
