name: Notification

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify
        run:
          curl -X POST
          -H "Content-Type:application/json"
          -H "X-GitHub-Event:${{github.event_name}}"
          -d @-
          ${{secrets.DISCORD_WEBHOOK_URL}} < ${{github.event_path}}

          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
