name: Notification

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Notify
      run: |
        curl -X POST \
          -H 'content-type:application/json' \
          -d '{"content":"computer-craft-deploy"}' \
          ${{secrets.DISCORD_WEBHOOK_URL}}
